language: c
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - make
      - gcc
      - coreutils
      - gcc-multilib
      - bc
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - linux-generic
      - linux-headers-generic

dist: trusty
  
sudo: True

script: uname -a && make help && make all && make install
