language: c

compiler:
  - gcc

os:
  - linux

before_script: export PATH=$PATH:$HOME/bin
 
addons:
  apt:
    packages:
      - make
      - gcc
      - coreutils
      - gcc-multilib
      - bc
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev

dist: trusty
  
sudo: required

script:
 - ./.travis/build.sh
 - make rebuild-lib
