language: c
compiler:
  - gcc

os:
  - linux

before_install:
 - sudo apt-get -y update
 - sudo apt-get -y install linux-generic linux-headers-generic
 
addons:
  apt:
    packages:
      - make
      - gcc
      - coreutils
      - gcc-multilib
      - bc
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev

dist: trusty
  
sudo: required

script: make help && sudo make all && sudo make install
