language: c

before_install:
 - sudo apt-get -y update
 - sudo apt-get -y install linux-headers-generic
 - git submodule update --init
 
addons:
  apt:
    packages:
      - make
      - gcc
      - coreutils
      - gcc-multilib
      - bc
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev

dist: trusty
  
sudo: required

script:
 - sudo ln -sf $(ls /lib/modules | sed 1q) /lib/modules/$(uname -r)
 - make
 - make bootstrap
 - make all
