language: c
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - make
      - gcc
      - coreutils
      - gcc-multilib
      - bc
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev

dist: trusty
  
sudo: True

script: make help && sudo make all && sudo make install
